Repository etclabscore/core-geth, pull requests merged in 2020-12, with the labels that each got.

#246 Convert YoloV2 flags to EIP-2315 and EIP-2929
  cmd/clef/main.go
  cmd/echainspec/main.go
  cmd/evm/internal/t8ntool/execution.go
  cmd/geth/consolecmd_test.go
  cmd/puppeth/wizard_genesis.go
  cmd/utils/flags.go
  core/state_processor.go
  core/vm/evm.go
  core/vm/jump_table.go
  core/vm/runtime/runtime.go
  eth/api_tracer.go
  integration/configurator_test.go
  params/config.go
  params/types/coregeth/chain_config.go
  params/types/coregeth/chain_config_configurator.go
  params/types/ctypes/configurator_iface.go
  params/types/genesisT/genesis.go
  params/types/goethereum/goethereum.go
  params/types/goethereum/goethereum_configurator.go
  params/types/multigeth/multigethv0_chain_config.go
  params/types/multigeth/multigethv0_chain_config_configurator.go
  params/types/parity/parity.go
  params/types/parity/parity_configurator.go
  tests/state_test_util.go
Labels: A3-inprogress ⏳

#243 Add an Ethash Fake sealing option for `—dev` mode, using `—dev.ethash`
  cmd/geth/main.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  consensus/ethash/ethash.go
  console/console_test.go
  eth/backend.go
  miner/miner_test.go
  params/genesis.go
Labels: A3-inprogress ⏳, P7-nicetohave 🐕

#185 rpc: add admin_maxPeers method
  eth/api.go
  eth/peer.go
  internal/web3ext/web3ext.go
Labels: M6-rpcapi 📣, P7-nicetohave 🐕, Y1-shouldupstream :outbox_tray:

#202 utils: refactor to use HomeDir fn
  cmd/utils/flags.go
Labels: A2-insubstantial 👶

#249 Fix/faucet discovery dns defaults
  cmd/faucet/faucet.go
Labels: F2-bug 🐞

#248 main: fix spurious error logs for empty bootnodes flag val
  cmd/faucet/faucet.go
Labels: F3-annoyance 💩, Q0-trivial 🎠

#260 Set default fallback for copydb 2nd ancient path arg
  cmd/geth/chaincmd.go
Labels: F8-enhancement 🎊

#263 core: abort duplicate ancient store writes
  core/blockchain.go
Labels: A0-pleasereview 🤓, Z5-intended 🎯

#265 Release/v1.11.20
  params/version.go
Labels: F9-release 🎈

#220 Feat/openrpc discover 20201024
  build/ci.go
  cmd/clef/main.go
  cmd/geth/consolecmd.go
  cmd/geth/main.go
  cmd/utils/flags.go
  eth/api.go
  eth/filters/bench_test.go
  ethclient/ethclient_test.go
  go.mod
  go.sum
  internal/ethapi/api.go
  internal/openrpc/openrpc_schema.go
  internal/openrpc/openrpc_schema_test.go
  node/config.go
  node/defaults.go
  node/node.go
  node/node_test.go
  node/openrpc.go
  node/openrpc_test.go
  params/vars/environment.go
  rpc/json.go
  rpc/openrpc.go
  rpc/server.go
Labels: M6-rpcapi 📣
