Repository etclabscore/core-geth, pull requests merged in 2020-10, with the labels that each got.

#194 Fix/ethstats parse url
  ethstats/ethstats.go
  ethstats/ethstats_test.go
Labels: F3-annoyance 💩, Y1-shouldupstream :outbox_tray:, Y2-pendingupstream :open_file_folder:

#195 propose mess mainnet block
  params/config_classic.go
Labels: A0-pleasereview 🤓, B7-releasenotes 📜, M2-config 📂

#197 Release/v1.11.15
  params/version.go
Labels: F9-release 🎈

#201 params: update bootnodes
  params/bootnodes_classic.go
  params/bootnodes_kotti.go
  params/bootnodes_mordor.go
Labels: A0-pleasereview 🤓, M2-config 📂

#200 miner: exit loop when downloader Done or Failed
  miner/miner.go
  miner/miner_test.go
Labels: A0-pleasereview 🤓, Y1-shouldupstream :outbox_tray:, Y2-pendingupstream :open_file_folder:

#208 Feat/refactor miner update
  miner/miner.go
  miner/miner_test.go
Labels: F6-refactor 📚

#209 forkid,params: set 1099 etc mainnet activation number
  core/forkid/forkid_test.go
  params/config_classic.go
Labels: A0-pleasereview 🤓, F9-release 🎈, M2-config 📂
