Repository etclabscore/core-geth, pull requests merged in 2020-11, with the labels that each got.

#223 Bit boundary fix for the DAG generation routine
  consensus/ethash/algorithm.go
Labels: Y2-pendingupstream :open_file_folder:

#226 Release/v1.11.17
  params/version.go
Labels: F9-release 🎈

#217 docs/core/releases.md: add documentation for release patterns
  docs/core/releases.md
Labels: F5-documentation 📑, F9-reference :bookmark_tabs:

#233 Release/v1.11.18
  params/version.go
Labels: F9-release 🎈

#244 Allow Ethereum protocol version to be set user configurable
  cmd/geth/main.go
  cmd/geth/misccmd.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  eth/backend.go
  eth/config.go
  eth/protocol.go
  ethstats/ethstats.go
Labels: F7-optimisation 💊, M2-config 📂, P7-nicetohave 🐕, Q2-easy 💃
