Repository etclabscore/core-geth, pull requests merged in 2020-02, with the labels that each got.

#29 Release/v1.9.10
  params/version.go
Labels: F9-release 🎈, M3-docs 📑

#27 Add new ETC mainnet bootnodes
  params/bootnodes_classic.go
Labels: A0-pleasereview 🤓, A2-insubstantial 👶, M2-config 📂

#40 README.md:update readme file
  README.md
Labels: A1-onice 🌨, F5-documentation 📑

#30 Release/v1.10.0 core
  params/version.go
Labels: A4-gotissues 💥, F9-release 🎈

#36 Fix/eip2200 sload gas again (and ECIP1086 nullified)
  core/vm/eips.go
  core/vm/gas_table_test.go
  core/vm/jump_table.go
  core/vm/jump_table_test.go
  params/config_kotti.go
  params/config_mordor.go
  params/types/ctypes/configurator_iface.go
  params/types/genesisT/genesis.go
  params/types/goethereum/goethereum_configurator.go
  params/types/multigeth/chain_config.go
  params/types/multigeth/chain_config_configurator.go
  params/types/multigethv0/multigethv0_chain_config_configurator.go
  params/types/parity/parity_configurator.go
  params/vars/protocol_params.go
Labels: A6-revertrevert 💀, A9-buythatmanabeer 🍻, M2-config 📂, M4-core ⛓

#41 discovery: add ETC support for discv4 DNS records
  cmd/devp2p/nodesetcmd.go
  cmd/utils/flags.go
  params/bootnodes_classic.go
  params/bootnodes_kotti.go
  params/bootnodes_mordor.go
Labels: F5-task 🎬, M2-config 📂

#45 Feat/update parity chainspecs
  Makefile
  params/parity.json.d/classic.json
  params/parity.json.d/commit.txt
  params/parity.json.d/foundation.json
  params/parity.json.d/goerli.json
  params/parity.json.d/kotti.json
  params/parity.json.d/morden.json
  params/parity.json.d/mordor.json
  params/parity.json.d/ropsten.json
  params/parity.json.d/sync-parity-remote.sh
  params/parity.json.d/transition_test.json
Labels: M2-config 📂
