Repository etclabscore/core-geth, pull requests merged in 2021-01, with the labels that each got.

#270 rm -rf cmd/puppeth
  build/ci.go
  cmd/puppeth/module.go
  cmd/puppeth/module_dashboard.go
  cmd/puppeth/module_ethstats.go
  cmd/puppeth/module_explorer.go
  cmd/puppeth/module_faucet.go
  cmd/puppeth/module_nginx.go
  cmd/puppeth/module_node.go
  cmd/puppeth/module_wallet.go
  cmd/puppeth/puppeth.go
  cmd/puppeth/ssh.go
  cmd/puppeth/wizard.go
  cmd/puppeth/wizard_dashboard.go
  cmd/puppeth/wizard_ethstats.go
  cmd/puppeth/wizard_explorer.go
  cmd/puppeth/wizard_faucet.go
  cmd/puppeth/wizard_genesis.go
  cmd/puppeth/wizard_intro.go
  cmd/puppeth/wizard_netstats.go
  cmd/puppeth/wizard_network.go
  cmd/puppeth/wizard_nginx.go
  cmd/puppeth/wizard_node.go
  cmd/puppeth/wizard_wallet.go
  docs/core/alltools.md
  params/confp/tconvert/doc.go
Labels: F7-footprint 🐾

#274 utils: MakeConsolePreloads agnostic of --jspath (console assets dir/docroot)
  cmd/utils/flags.go
Labels: F2-bug 🐞, Y1-shouldupstream :outbox_tray:

#278 cmd/faucet/main: fix eth backend API initialization
  cmd/faucet/faucet.go
Labels: F2-bug 🐞

#295 node: add test for the discovery endpoint to validate OpenRPC compliance
  go.mod
  go.sum
  node/node_test.go
  node/testdata/open-rpc-meta-schema-1.14.0.json
Labels: F4-tests 💻, M6-rpcapi 📣

#302 .github/workflows: don't build docs on PRs
  .github/workflows/docs-deploy.yml
Labels: F2-bug 🐞, M3-docs 📑

#296 README: bump OpenRPC badge version
  README.md
  docs/index.md
Labels: F5-documentation 📑

#304 Feat/ecip1100 nodisable
  cmd/geth/config.go
  cmd/geth/main.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  core/blockchain.go
  core/blockchain_af.go
  eth/backend.go
  eth/config.go
  eth/sync.go
  eth/sync_test.go
Labels: A0-pleasereview 🤓, M2-config 📂, M4-core ⛓

#307 Release/v1.11.21
  params/version.go
Labels: F9-release 🎈
