Repository etclabscore/core-geth, pull requests merged in 2021-05, with the labels that each got.

#356 Test for OpenRPC subscription methods on trace/debug modules
  docs/JSON-RPC-API/modules/admin.md
  docs/JSON-RPC-API/modules/debug.md
  docs/JSON-RPC-API/modules/eth.md
  docs/JSON-RPC-API/modules/ethash.md
  docs/JSON-RPC-API/modules/miner.md
  docs/JSON-RPC-API/modules/net.md
  docs/JSON-RPC-API/modules/personal.md
  docs/JSON-RPC-API/modules/trace.md
  docs/JSON-RPC-API/modules/txpool.md
  docs/JSON-RPC-API/modules/web3.md
  ethclient/docsgen_test.go
  ethclient/ethclient_test.go
  node/openrpc.go
Labels: A3-inprogress ⏳, F4-tests 💻

#367 Add OverrideMagneto flag
  cmd/geth/config.go
  cmd/geth/main.go
  cmd/utils/flags.go
  core/genesis.go
  eth/backend.go
  eth/ethconfig/config.go
Labels: P3-nextrelease :ship:

#375 cmd/geth,internal/cmdtest: add KillTimeout field to TestCmd struct
  cmd/geth/consolecmd_cg_test.go
  internal/cmdtest/test_cmd.go
Labels: F4-tests 💻

#383 docs/core: fixup! link path for JSONRPC docs
  docs/core/index.md
Labels: F5-documentation 📑, Q0-trivial 🎠

#380 p2p/nat: skip TestUPNP in non-CI envs if discover fails
  p2p/nat/natupnp_test.go
Labels: A7-looksgoodtestsfail 🤖, Y1-shouldupstream :outbox_tray:, Y2-pendingupstream :open_file_folder:
