Repository etclabscore/core-geth, pull requests merged in 2021-03, with the labels that each got.

#328 .travis.yml: divide arm job into alphabetical segments
  .travis.yml
  docs/JSON-RPC-API/openrpc.md
Labels: A0-pleasereview 🤓, M1-ci 🙉

#326 bump Travis and Appveyor ci Go version to go1.16
  .travis.yml
  accounts/abi/bind/bind_test.go
  appveyor.yml
Labels: A0-pleasereview 🤓

#330 docs/developers: draft Add Network tutorial
  docs/developers/add-network.md
Labels: F5-documentation 📑

#338 docs/developers: fixup Add-Network tutorial
  docs/developers/add-network.md
Labels: F5-documentation 📑

#333 internal/ethapi: don't omit empty txes, uncles from getBlock responses
  ethclient/ethclient_test.go
  internal/ethapi/api.go
Labels: A0-pleasereview 🤓

#340 .github/workflows: fix not-gofmt'd bootnodes files after audit
  .github/workflows/audit-bootnodes.yml
Labels: M1-ci 🙉

#342 ethclient: fix missing doublequote in example
  ethclient/docsgen_test.go
Labels: M3-docs 📑, Q0-trivial 🎠

#343 .github/workflows: fix bash condition syntax for showing git diff
  .github/workflows/audit-bootnodes.yml
Labels: M1-ci 🙉, Q0-trivial 🎠

#347 fix ARM64 test panics
  cmd/geth/accountcmd_test.go
  cmd/geth/consolecmd.go
  cmd/geth/consolecmd_cg_test.go
  cmd/geth/consolecmd_test.go
  cmd/geth/dao_test.go
  cmd/geth/genesis_test.go
  cmd/geth/les_test.go
  go.mod
  go.sum
Labels: F4-tests 💻, M0-build 🏗

#350 docs: Upgrade MkDocs requirements
  requirements-mkdocs.txt
Labels: M3-docs 📑

#341 Fix/eth_getBlockByNumber and eth_getUncle... nullable fields
  ethclient/ethclient_cg_test.go
  ethclient/ethclient_test.go
  internal/ethapi/api.go
Labels: F4-tests 💻, M1-ci 🙉, M6-API:RPC 📣

#352 .travis.yml: fix typos in arm64 job go version (should be 1.16.x)
  .travis.yml
Labels: M1-ci 🙉

#336 ci: comparative benchmarks for vm, core, and trie operations
  .github/workflows/bench-core.yml
  .github/workflows/bench-trie.yml
  .github/workflows/bench-vm.yml
  build/bench-suite-compress.sh
  tests/vm_bench_test.go
Labels: F7-optimisation 💊, M1-ci 🙉
